[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo_mysql", "nodejs_22"]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-interaction",
  "npm ci",
  "npm run build"
]

[start]
cmd = "php artisan migrate --force"
